- src/feature/commit/store/useCommitStore.js
- src/pages/Home/api/getCommitList.js
- src/pages/Home/index.jsx
- src/shared/constants/messages.js
- src/shared/utils/extractGitInfoFromURL.js
🔗 이슈 링크: https://github.com/git-marvel/commit-guardians-client/issues/9
사용자가 Github respository의 주소를 입력하고 버튼을 누르면, 해당 repository의 commit 목록들이 전역 상태로 저장됩니다.
- Zustand를 이용하여 commit 목록을 저장할 store와 state를 생성 하였습니다.
- Error message를 저장할 파일을 생성하였습니다.
- UI가 적용되지 않았습니다.
- UI, UX 작업시에 throw한 error을 기반으로 Error 메시지의 처리를 하시면 좋겠습니다.
X
---
> feat: Github respository의 주소 입력에 따른 commit 목록 요청 및 응답 데이터 저장

- .gitignore
- package.json
- src/app/router.jsx
- src/features/commitBadge/components/CopyBadge.jsx
- src/features/commitBadge/hooks/useCopyBadge.jsx
- src/features/commitBadge/services/index.js
- src/pages/MyCommitBadge/index.jsx
- src/pages/MyCommitScoreboard/index.jsx
- src/pages/NotFound/index.jsx
- src/shared/components/Badge.jsx
- src/shared/components/Button.jsx
- src/shared/components/SnackBar.jsx
- src/shared/config/index.js
- tailwind.config.js
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/15
- 결과 페이지에서 보여줄 뱃지와 깃허브 repository README에 붙여넣기할 링크를 복사할 수 있는 기능을 추가했습니다.
- env 파일을 gitignore 에 추가했습니다.
- 머지되면 `npm i` 로 의존성 추가설치해주세요!
---
> feat: 뱃지 UI 만들기및 클립보드 복사 기능

- src/entities/commitType/services/index.js
- src/pages/Home/api/index.js
- src/pages/Home/index.jsx
- src/shared/utils/extractGitInfoFromURL.js
🔗 이슈 링크: https://github.com/git-marvel/commit-guardians-client/issues/10
응답 받아 저장한 커밋 목록을 바탕으로, tag를 통해 검사할 커밋들의 변경 내용(diff)를 비동기로 요청합니다.
변경 내용을 순차적으로 전역 state로 저장합니다.
- change의 map type이 sessionStorage에 올바르지 않아 array로 바꾸어 주었습니다.
- Organization name을 owner로, repository name을 repo로 통일 하였습니다.
- getCommitDiff 함수의 ref 파라미터를 sha로 변경하였습니다.
- 없음
---
> feat: 커밋 목록들 중, 커밋 퀄리티를 검사할 수 있는 커밋들만 저장하기

- package.json
- src/pages/Home/api/index.js
🔗 이슈 링크: https://github.com/git-marvel/commit-guardians-client/issues/35
Fetch 함수를 axios 패키지의 axios 함수로 대체하여 다음과 같은 효과를 기대 할 수 있습니다.
- 스크립트가 어떠한 역할을 하는지 가독성 개선이 있습니다.
- json() 비동기 메서드를 따로 사용하지 않고 정보를 취득할 수 있습니다.
위의 대체와 함께 영향을 받은 변수, 함수명의 변경이 있었습니다.
- axios 패키지가 추가되어, merge된 branch에서는 추가로 패키지 설치가 필요합니다.
- 없음
---
> refactor: Fetch를 axios로 변경

- src/pages/Home/hooks/useValidateCommit.jsx
- src/pages/Home/index.jsx
- src/shared/components/Loading.jsx
- tailwind.config.js
🔗 이슈 링크 [#33](https://github.com/git-marvel/commit-guardians-client/issues/33)
- 커밋 메시지에 대한 처리를 하는 동안 보여질 로딩 페이지입니다.
---
> feat: 대용량 데이터 처리 로직에 대한 응답을 기다리는 동안 보여질 로딩 UI 구현

- src/entities/score/services/index.js
- src/features/commit/store/useCommitStore.js
- src/pages/Home/api/index.js
- src/pages/Home/hooks/useValidateCommit.jsx
- src/pages/MyCommitBadge/index.jsx
🔗 이슈 링크: https://github.com/git-marvel/commit-guardians-client/issues/14
커밋 검증 결과 페이지로 이동하는 버튼 안에 100점을 맞은 커밋의 개수를 표시한다.
변경된 버튼 모습 (null state 반영, 실제로는 숫자가 출력 될 때만 작동)
수정 된 store에 저장된 모습
* 80% 이상 : 커밋규칙왕
* 50% 이상 : 커밋노력파
* 30% 이상 : 커밋 뉴비
* 나머지 : 커밋 개성파
- getTotalQualityPercent는 현재 사용되지 않고, 채점 과정이 완료되면 사용 될 수 있습니다.
- Zustand store에 변경사항이 있으니 사용에 주의 해주시기 바랍니다.
---
> feat: 100%인 커밋들 수 / 검사한 모든 커밋들 수 계산하기

- src/entities/change/changeEntity.js
- src/entities/commit/commitEntity.js
- src/entities/commit/services/scoreRemoveCommitType.js
- src/features/commit/components/CommitValidationMark.jsx
- src/pages/Home/hooks/useValidateCommit.jsx
- src/pages/Home/index.jsx
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/4
- 커밋 타입이 Remove 인 경우, 커밋 퀄리티점수를 확인할 수 있습니다.
- 이후 docs 타입의 경우를 작성할 때, `commitEntity` 안의 `setCommitQualityScore` 함수에 삽입하면 됩니다!
---
> feat: 커밋 타입이 Remove 인 경우, 커밋 퀄리티점수를 계산하는 로직을 추가

- src/entities/commit/services/__tests__/scoreRemoveCommitType.test.js
- src/entities/commit/services/scoreRemoveCommitType.js
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/23
- 커밋 타입 remove 관련 로직에 대한 검증을 진행했습니다.
- @shkimjune test 코드를 참고해주세요!
---
> test: 커밋타입 Remove 에 대한 로직 테스트 코드 작성

- src/entities/commit/commitEntity.js
- src/entities/commit/services/index.js
- src/entities/commit/services/scoreDocsCommitType.js
- src/pages/Home/hooks/useValidateCommit.jsx
🔗 이슈 링크 [#5](https://github.com/git-marvel/commit-guardians-client/issues/5)
- 커밋 타입 docs인 커밋의 점수를 계산하는 함수입니다.
* 이미지 파일 - .img, .png, .jpeg, .svg, . ai
* .pdf
* .docs
* .md, mdx
---
> feat: 커밋 타입이 docs인 커밋의 퀄리티 계산 로직 추가

- src/entities/commit/commitEntity.js
- src/entities/commit/services/scoreTestCommitType.js
🔗 이슈 링크 [#7](https://github.com/git-marvel/commit-guardians-client/issues/7)
- test 커밋 타입인 경우의 커밋의 퀄리티 점수를 계산하는 로직입니다.
* 예시
```
.test.js, .test.ts, .test.tsx
.spec.js, .spec.ts, e2e.spec.ts, spec.cy.js 
*.mock.js, *.mock.json
```
---
> feat: 커밋타입 test인 커밋의 퀄리티 점수 계산 로직 작성

- src/pages/Home/index.jsx
- src/shared/components/BarGraph.jsx
🔗 이슈 링크 x
- 처음 막대그래프가 넘어가지 않도록 max 값을 설정해둔 상수를 조정하여, 레이아웃을 넘어가지 않도록 합니다.
x
---
> design: 막대그래프 최대값 제한 수정 및 홈 레이아웃 개선

- src/entities/commit/services/index.js
- src/features/commit/components/AvatarValue.jsx
- src/features/commit/components/ChangesValue.jsx
🔗 이슈 링크 x
- commit author 가 가끔 null 로 들어올 때가 있었다. 예시레포) [three.js](https://github.com/mrdoob/three)
---
> fix: commit author 가 null 일 경우 로직 및 화면 처리

- package.json
- src/entities/commit/commitEntity.js
- src/entities/commit/services/scoreStyleCommitType.js
🔗 이슈 링크: https://github.com/orgs/git-marvel/projects/1/views/1?pane=issue&itemId=85651858&issue=git-marvel%7Ccommit-guardians-client%7C6
style 타입을 가지는 commit들의 점수를 계산하는 기능을 추가하였습니다.
바뀐 단어가 단순 이름의 변경인지 사용하는 대상이 변경되어있는지 diff만으로 판단 불가능하다.
줄을 바꾸게 되면 다음과 같은 이슈가 발생한다.
- change가 하나로 묶이지 않는다. (change를 모두 저장해 놓고 문자열을 비교해야 해결 가능)
- scope가 변경된다면, 단순 style이 아니라 feat 혹은 refactor로 취급될 수 있는데, diff만으로 판단 불가능 하다.
if문을 간단히 표시하기 위해 중괄호를 생략하고 작성하는 경우가 종종있는데, scope 제한이 명시적으로 되어있지 않아 원치않는 버그를 유발시킬 수 있다. 개인적으로는 refactor에 더 가깝다 생각하는데, style로 생각하면 생각할 수 있는 부분이다.
[[참고하면 좋은 글](https://stackoverflow.com/questions/2125066/is-it-a-bad-practice-to-use-an-if-statement-without-curly-braces)](https://stackoverflow.com/questions/2125066/is-it-a-bad-practice-to-use-an-if-statement-without-curly-braces)
"prettier", "eslint", …
> feat: style 체크 로직 작성

- src/entities/commit/services/scoreTestCommitType.js
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/7
- 판단 기준 확장
- "tests" 키워드 추가
- 통과 기준 수정: 파일명의 끝에 test커밋인지 판단하는 키워드가 포함되어 있다면 통과
```
// 예시 (파일 확장자와 앞 부분의 경로를 제외)
".../auth_repository_imp_test.dart"  ->  auth_repository_imp_test
".../ResultServiceTest.java"  ->  ResultServiceTest
".../.../info_content.test.tsx.snap"  ->  info_content.test.tsx
```
* 잘라낸 파일명에 `"test", "tests", "spec", "mock"` 가 있는지 확인
---
> feat: test 커밋타입 키워드 추가

- src/entities/commit/services/__tests__/diffObj.mock.js
- src/entities/commit/services/scoreDocsCommitType.js
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/5
- 테스트 코드 작업 중 문서작성 관련 추가 파일확장자(.rst)를 알게 되어 추가했습니다.
- `.rst`
- 주로 Python 커뮤니티에서 사용되는 기술 문서 파일 형식으로 reStructuredText 마크업 언어로 작성된 텍스트 파일의 확장자입니다. 
- [reStructuredText documentation](https://docutils.sourceforge.io/rst.html#reference-documentation)
---
> feat: docs 커밋 타입 파일 확장자에 .rst 추가

- src/entities/commit/services/__tests__/scoreStyleCommitType.test.js
🔗 이슈 링크: https://github.com/git-marvel/commit-guardians-client/pull/61
커밋 타입 style 관련 로직에 대한 검증을 진행했습니다.
"prettier", "eslint", "config”와 같은 단어가 파일명에 있는 경우 style을 통일화 하기 위한 파일의 변경으로 볼 수 있다. chore혹은 docs와 겹칠 수 있는 부분이지만, style로 보는게 적합하다 본다.
, , ' , " , \n , ; 과 같은 특수 문자만 변경이 있는 경우 올바르다고 채점 한다.
Google의 diff-match-patch 패키지를 이용해서 문자열의 변화를 추출하고, 해당 변화가 조건에 맞는 변경만 있을 시에 true로 반환한다.
변경된 문자열이 console.log 과 관련된 경우 true로 반환
아래와 같은 위치 변경에 대해 문자열을 추출하고 비교한다.
object의 property들의 위치 변경 /\{\s([^}]*)\s\}/
해당 추출된 문자열을 split하여 각 요소들을 리스트로 만들고, set을 이용하여 모두 일치 하는지 비교한다.
---
> test: scoreStyleCommitType 함수에 대한 test 코드 작성

- src/entities/commit/services/scoreDocsCommitType.js
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/5
- docs타입에 대한 로직 최적화 (scoreDocsCommitType)
---
> refactor: docs타입에 대한 로직 최적화

- src/entities/score/services/index.js
- src/features/commit/store/useCommitStore.js
- src/features/commitBadge/hooks/useCopyBadge.jsx
- src/features/commitBadge/services/index.js
- src/pages/Home/hooks/useValidateCommit.jsx
- src/pages/MyCommitBadge/index.jsx
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/71
- 총 점수를 화면에 보여주는 기능이 있습니다.
- commit total score 와 관련있는 변수명들을 직관적으로 바꾸었습니다.
- 변수명을 확인해주세요.
---
> feat: 총 점수를 화면에 보여주는 기능 및 commit total score 와 관련된 변수명 변경

- src/features/commit/components/CommitQualityScore.jsx
- src/features/commitBadge/hooks/useCopyBadge.jsx
- src/features/githubAPIStatus/components/GithubAPIStatus.jsx
- src/pages/Home/index.jsx
- src/pages/MyCommitScoreboard/components/ScoreBoardRow.jsx
- src/pages/MyCommitScoreboard/index.jsx
- src/shared/components/Footer.jsx
🔗 이슈 링크
- 디테일 페이지에 대한 디자인 수정 (github API status 링크로 이동, 정갈한 디자인)
- 없습니다.
---
> design: 디테일 페이지에 대한 디자인 수정 (github API status 링크로 이동, 정갈한 디자인)

- src/entities/commit/services/index.js
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/74
- 템플릿 형식 커밋과 깃모지 사용시에도 문제 없이 서비스 사용할 수 있도록 버그를 해결했습니다.
---
> fix: 템플릿 형식 커밋과 GitMoji 사용시,  타입검사가 불가능했던 버그 해결

- src/entities/score/services/index.js
🔗 이슈 링크 : https://github.com/git-marvel/commit-guardians-client/issues/69
점수의 계산 방식을 100점 commit의 비율이 아닌, commit 점수들의 평균으로 변경하였습니다.
---
> feat: 총 점수의 계산 방식 변경

- src/entities/commit/commitEntity.js
- src/entities/commit/services/index.js
- src/features/commit/components/CommitFormatStyleValue.jsx
- src/features/commit/components/CommitMessageValue.jsx
- src/features/commit/hooks/useCheckCommitFormatStyle.jsx
- src/features/commit/store/useCommitStore.js
- src/features/repository/components/RepositoryLinkTag.jsx
- src/pages/Home/hooks/useValidateCommit.jsx
- src/pages/MyCommitScoreboard/index.jsx
- src/shared/components/HomeButton.jsx
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/77
- 디테일 페이지에서 커밋메세지의 형식을 보여줍니다. 
- x
---
> feat: 커밋 formatStyle 도 디테일 화면에서 보여주기

- src/entities/commit/enum/commitFormatStyleEnum.js
- src/entities/commit/services/index.js
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/82
- prefix-style 스코프가 존재해도, 타입 검사가능하도록 버그픽스했습니다.
- 첫단어로 무조건 잘라 검사하기 때문에 `simple-text-style` 이면 splitWith 을 "" 빈문자열로 만들어서 자르도록 합니다.
- 참고링크: https://github.com/mwanago/nestjs-typescript
- 참고링크: https://github.com/wonderful123/ESP32-Flow-Meter-Pulse-Multipler
- x
---
> fix: prefix-style 스코프가 존재해도, 타입 검사가능하도록 문제해결 및 simple-text-style 의 splitWith 재검토

- src/features/commit/components/InfoValue.jsx
- src/features/commit/constants/index.js
- src/pages/MyCommitScoreboard/components/ScoreBoardHeader.jsx
- src/pages/MyCommitScoreboard/components/ScoreBoardRow.jsx
- src/shared/components/InfoIcon.jsx
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/80
- 사용자가 scoreBoard에서 컬럼값 옆 아이콘을 마우스 호버하면 추가 설명이 나타납니다.
- time 변수
-  [Date.prototype.toTimeString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toTimeString) 반환값의 앞 부분은 항상 HH:MM:SS 2자리씩 고정되어 있어서 그에 따라 slice()의 인덱스 값을 정하게 됐습니다.
---
> feat: 디테일 페이지 컬럼값에 추가 정보를 담은 Tooltip UI 구현

- src/features/commit/components/InfoValue.jsx
- src/features/commit/components/ShaHoverBox.jsx
- src/features/commitBadge/components/CopyBadge.jsx
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/80
- 예) 복사아이콘, 정보 아이콘 등 메시지가 나타나도록 지정된 아이콘이 아닌 곳에서 마우스 호버됐을 때 메시지가 보여지는 문제입니다.
> fix: 정보표시 아이콘이 아닌 곳에서 마우스 호버됐을 때도 툴팁이 보여지는 문제 해결

- src/entities/commit/services/__tests__/scoreRemoveCommitType.test.js
- src/entities/commit/services/scoreRemoveCommitType.js
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/4
- scoreBoard의 커밋 점수가 마이너스가 발생하는 오류를 해결했습니다.
---
> fix: remove타입 점수 계산 로직 수정

- src/entities/commit/services/scoreDocsCommitType.js
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/90
- docs 타입인 커밋을 체크할 때 문서 주석(JSDoc, dartdoc)을 변경했을 경우도 인정되도록 추가되었습니다.
---
> feat: 문서 주석(JSDoc, dartdoc) 수정 시 docs 타입으로 판단

- src/entities/commit/services/__tests__/scoreRemoveCommitType.test.js
- src/entities/commit/services/scoreRemoveCommitType.js
- src/pages/Home/api/index.js
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/4
- remove타입 체크 로직이 수정된 후 더 이상 쓰이지 않는 파라미터를 삭제했습니다.
---
> refactor: remove타입 체크 로직에서 쓰이지 않는 파라미터 삭제

- src/app/router.jsx
- src/pages/Home/hooks/useValidateCommit.jsx
- src/shared/store/usePersistentStore.js
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/100
- 새로고침시에도 이전값을 라우팅하여 볼 수 있습니다.
x
---
> feat: 새로고침시에도 이전값을 라우팅하여 볼 수 있는 기능 추가

- src/pages/Home/api/index.js
- src/shared/api/tokenManager.js
- src/shared/constants/index.js
🔗 이슈 링크 https://github.com/git-marvel/commit-guardians-client/issues/41
- GitHub API 요청 시 여러 토큰을 분산 사용하여 Rate Limit을 관리하는 로직 구현하여 사용자경험을 증진시켰습니다.
- 개발환경 화면에서 콘솔을 확인해보면, 요청수에 따라 토큰이 알아서 바뀌어 분산요청을 하는 것을 확인할 수 있습니다.
- **환경변수 설정하셔야 합니다! **
---
> feat: GitHub API 요청 시 여러 토큰을 분산 사용하여 Rate Limit을 관리하는 로직 구현

- src/features/commit/components/ChangesValue.jsx
- src/shared/components/BarGraph.jsx
🔗 이슈 링크
- 결과 목록 페이지: 전체 changes 의 개수로 인해 barGraph의 최대 길이로 나타낼 수 있는 범위를 넘었을 경우에 제대로 표시되지 않는 에러를 수정했습니다.
---
> fix: changes의 barGraph의 길이가 최대 width 보다 큰 경우 비율로 표시

- src/entities/score/services/__tests__/getCommitSummary.test.js
[🔗 이슈 링크](https://github.com/git-marvel/commit-guardians-client/issues/19)
- getCommitSummary 커밋목록을 받아 총점을 계산하는 로직 테스트 코드 작성했습니다.
---
> test: getCommitSummary 커밋목록을 받아 총점을 계산하는 로직 테스트 코드 작성
